"""Static, code-managed settings metadata (Issue #102).

Explanations for every user-facing configuration setting: what it is for,
which features it affects, what breaks when it is missing or invalid, and
how to fix it. This registry is the single source the per-screen assistant
uses to explain settings; the text is authored in code — never generated by
an LLM (Issue #102 acceptance criterion).

The registry is shared with the deterministic diagnostics service
(Issue #101): every env var a diagnostics check lists in `related_env`
must have an entry here, and `related_checks` cross-references the
diagnostics `check_id` vocabulary. Tests enforce that contract.

probe-agent:
  role: Static settings-explanation metadata registry
  capability: system-configuration-help
  element_type: core
  consumers: [control-server, dashboard]
  operation_kind: read
  state_effects: []
  probe_value: Verify every diagnostics-referenced env var has a static, non-LLM explanation with impact and remediation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

# Requiredness vocabulary (finite set):
#   required     - the feature it belongs to cannot work without it
#   conditional  - required only under an explicitly stated condition
#   optional     - has a safe default
REQUIREDNESS_VALUES = ("required", "conditional", "optional")

# Categories align with diagnostics check categories where possible.
SETTING_CATEGORIES = ("repository", "database", "llm", "intelligence", "auth")


@dataclass(frozen=True)
class SettingMetadata:
    key: str
    display_name: str
    category: str
    requiredness: str
    description: str
    impact: str
    remediation: str
    valid_values: Optional[List[str]] = None
    validation_rule: str = ""
    related_checks: List[str] = field(default_factory=list)
    related_pages: List[str] = field(default_factory=list)
    related_pipeline_steps: List[str] = field(default_factory=list)
    docs_link: str = ""


_REASONING_STEPS = [
    "documentation_claims_scanned",
    "docs_code_reconciled",
    "capability_hierarchy_ready",
]

SETTINGS_METADATA: List[SettingMetadata] = [
    SettingMetadata(
        key="PROBE_REPOSITORY_ROOTS",
        display_name="Repository roots",
        category="repository",
        requiredness="required",
        description=(
            "Absolute path(s), separated by the OS path separator, under which "
            "the Control Server discovers Git repositories to analyze. All "
            "repository reads are pinned to committed content inside these "
            "roots."
        ),
        impact=(
            "Without it, repository selection, snapshots, and every System "
            "Understanding step that reads code fail or stay missing."
        ),
        remediation=(
            "Set PROBE_REPOSITORY_ROOTS to the directories containing your Git "
            "repositories (readable by the Control Server process) and restart "
            "the server. In Docker Compose, mount the host directory referenced "
            "by PROBE_REPOSITORY_HOST_ROOT."
        ),
        validation_rule="Each path must exist, be readable, and be a directory.",
        related_checks=["repository_roots", "repository_config"],
        related_pages=["/repository"],
        related_pipeline_steps=["repository_configured", "snapshot_ready"],
        docs_link="/connect-sdk",
    ),
    SettingMetadata(
        key="PROBE_DB_PATH",
        display_name="Database path",
        category="database",
        requiredness="optional",
        description=(
            "Filesystem path of the SQLite database that stores traces, "
            "policies, snapshots, and intelligence runs. Defaults to a local "
            "file next to the server."
        ),
        impact=(
            "If the path or its directory is not writable, every write "
            "operation (traces, policies, snapshots, runs) fails."
        ),
        remediation=(
            "Point PROBE_DB_PATH at a writable location or fix the "
            "directory/file permissions."
        ),
        validation_rule="Directory must exist and be writable; existing file must be read/writable.",
        related_checks=["database_storage"],
    ),
    SettingMetadata(
        key="LLM_PROVIDER",
        display_name="LLM provider (Generate & Evaluate)",
        category="llm",
        requiredness="required",
        description=(
            "Provider used by Generate & Evaluate and, when INTELLIGENCE_LLM_* "
            "is empty, the fallback provider for Feature Intelligence "
            "reasoning."
        ),
        impact=(
            "An unsupported provider or missing API key makes candidate "
            "generation and reasoning-backed features fail at call time. "
            "'mock' produces deterministic test data only and blocks "
            "reasoning-required pipeline steps."
        ),
        remediation=(
            "Set LLM_PROVIDER to one of the supported providers and configure "
            "the matching API key."
        ),
        valid_values=["openai", "anthropic", "gemini", "mock"],
        related_checks=["llm_base_config", "intelligence_llm_config"],
        related_pages=["/generation"],
    ),
    SettingMetadata(
        key="LLM_MODEL",
        display_name="LLM model (Generate & Evaluate)",
        category="llm",
        requiredness="optional",
        description=(
            "Model id used by Generate & Evaluate; defaults to a per-provider "
            "model when empty. Also the fallback model for Feature "
            "Intelligence when INTELLIGENCE_LLM_MODEL is empty."
        ),
        impact=(
            "An invalid model id fails at call time; the failure appears in "
            "the last observed run error of the diagnostics."
        ),
        remediation="Set a model id that belongs to the configured LLM_PROVIDER.",
        validation_rule="Model family should match LLM_PROVIDER (e.g. gpt-* for openai, claude-* for anthropic, gemini-* for gemini).",
        related_checks=["llm_base_config", "intelligence_llm_config"],
        related_pages=["/generation"],
    ),
    SettingMetadata(
        key="LLM_API_KEY",
        display_name="LLM API key (generic)",
        category="llm",
        requiredness="conditional",
        description=(
            "Generic API key used for whichever LLM provider is configured. "
            "Provider-specific keys (OPENAI_API_KEY, ANTHROPIC_API_KEY, "
            "GEMINI_API_KEY) are used when this is empty."
        ),
        impact=(
            "Required for every non-mock provider; without any matching key, "
            "all LLM calls fail with an authentication error."
        ),
        remediation=(
            "Set LLM_API_KEY (or the provider-specific key) for the configured "
            "provider and restart the Control Server."
        ),
        validation_rule="Required unless LLM_PROVIDER=mock or a provider-specific key is set.",
        related_checks=["llm_base_config", "intelligence_llm_config", "llm_last_run"],
        related_pages=["/generation", "/system-understanding"],
    ),
    SettingMetadata(
        key="LLM_TIMEOUT",
        display_name="LLM request timeout (seconds)",
        category="llm",
        requiredness="optional",
        description="Timeout in seconds for LLM API requests (default 120).",
        impact=(
            "A non-numeric or non-positive value is ignored/flagged; a too "
            "small value makes long generations fail with timeouts."
        ),
        remediation="Set a positive number of seconds, e.g. 120.",
        validation_rule="Positive number.",
        related_checks=["llm_base_config"],
    ),
    SettingMetadata(
        key="LLM_BASE_URL",
        display_name="LLM base URL",
        category="llm",
        requiredness="optional",
        description=(
            "Override for the provider API base URL (self-hosted gateways or "
            "compatible endpoints). Empty uses the provider default."
        ),
        impact="A wrong URL makes every LLM call fail at request time.",
        remediation="Leave empty for the official provider endpoint, or set a reachable base URL.",
        related_checks=["llm_base_config"],
    ),
    SettingMetadata(
        key="INTELLIGENCE_LLM_PROVIDER",
        display_name="Intelligence reasoning provider",
        category="intelligence",
        requiredness="conditional",
        description=(
            "Provider for Feature Intelligence reasoning (documentation "
            "indexing, claim scanning, docs-code reconciliation, capability "
            "hierarchy). Falls back to LLM_PROVIDER when empty."
        ),
        impact=(
            "Reasoning-required pipeline steps fail or stay blocked without a "
            "valid reasoning provider; there is no heuristic fallback."
        ),
        remediation=(
            "Set INTELLIGENCE_LLM_PROVIDER (openai/anthropic/gemini) together "
            "with a reasoning-capable INTELLIGENCE_LLM_MODEL, then run "
            "Build / Refresh in System Understanding."
        ),
        valid_values=["openai", "anthropic", "gemini", "mock"],
        related_checks=["intelligence_llm_config", "llm_last_run"],
        related_pages=["/system-understanding"],
        related_pipeline_steps=_REASONING_STEPS,
    ),
    SettingMetadata(
        key="INTELLIGENCE_LLM_MODEL",
        display_name="Intelligence reasoning model",
        category="intelligence",
        requiredness="conditional",
        description=(
            "Reasoning-capable model id for Feature Intelligence (e.g. OpenAI "
            "o1/o3/o4/gpt-5 family, Anthropic claude-3-7/claude-4/opus/sonnet-4 "
            "family, Gemini 2.5+). Falls back to LLM_MODEL when empty."
        ),
        impact=(
            "A non-reasoning or wrong-family model blocks documentation "
            "indexing, claim scanning, and capability hierarchy generation."
        ),
        remediation=(
            "Set a reasoning-capable model id that matches the effective "
            "intelligence provider, then re-run the System Understanding build."
        ),
        validation_rule=(
            "Model family must match the effective intelligence provider and "
            "be reasoning-capable (checked by the intelligence_llm_config "
            "diagnostic)."
        ),
        related_checks=["intelligence_llm_config", "llm_last_run"],
        related_pages=["/system-understanding"],
        related_pipeline_steps=_REASONING_STEPS,
    ),
    SettingMetadata(
        key="INTELLIGENCE_LLM_TIMEOUT",
        display_name="Intelligence request timeout (seconds)",
        category="intelligence",
        requiredness="optional",
        description="Timeout in seconds for Feature Intelligence LLM requests.",
        impact="Non-positive/non-numeric values are flagged; small values cause run failures.",
        remediation="Set a positive number of seconds, e.g. 120.",
        validation_rule="Positive number.",
        related_checks=["intelligence_llm_config"],
        related_pages=["/system-understanding"],
    ),
    SettingMetadata(
        key="INTELLIGENCE_MAX_OUTPUT_TOKENS",
        display_name="Intelligence max output tokens",
        category="intelligence",
        requiredness="optional",
        description=(
            "Maximum output tokens for Feature Intelligence generations "
            "(e.g. repository draft generation)."
        ),
        impact="Too small values truncate reasoning output and can fail structured-output validation.",
        remediation="Set a positive integer suitable for the configured model.",
        validation_rule="Positive integer.",
        related_checks=["intelligence_llm_config"],
        related_pages=["/system-understanding"],
    ),
    SettingMetadata(
        key="OPENAI_API_KEY",
        display_name="OpenAI API key",
        category="llm",
        requiredness="conditional",
        description="Provider-specific API key used when the effective provider is openai and LLM_API_KEY is empty.",
        impact="Without a usable key, OpenAI calls fail with an authentication error.",
        remediation="Set OPENAI_API_KEY or the generic LLM_API_KEY.",
        validation_rule="Required when provider=openai and LLM_API_KEY is empty.",
        related_checks=["llm_base_config", "intelligence_llm_config"],
    ),
    SettingMetadata(
        key="ANTHROPIC_API_KEY",
        display_name="Anthropic API key",
        category="llm",
        requiredness="conditional",
        description="Provider-specific API key used when the effective provider is anthropic and LLM_API_KEY is empty.",
        impact="Without a usable key, Anthropic calls fail with an authentication error.",
        remediation="Set ANTHROPIC_API_KEY or the generic LLM_API_KEY.",
        validation_rule="Required when provider=anthropic and LLM_API_KEY is empty.",
        related_checks=["llm_base_config", "intelligence_llm_config"],
    ),
    SettingMetadata(
        key="GEMINI_API_KEY",
        display_name="Gemini API key",
        category="llm",
        requiredness="conditional",
        description="Provider-specific API key used when the effective provider is gemini and LLM_API_KEY is empty.",
        impact="Without a usable key, Gemini calls fail with an authentication error.",
        remediation="Set GEMINI_API_KEY or the generic LLM_API_KEY.",
        validation_rule="Required when provider=gemini and LLM_API_KEY is empty.",
        related_checks=["llm_base_config", "intelligence_llm_config"],
    ),
    SettingMetadata(
        key="CONTROL_ADMIN_USERNAME",
        display_name="Bootstrap admin username",
        category="auth",
        requiredness="conditional",
        description=(
            "Username of the admin user created at first startup (together "
            "with CONTROL_ADMIN_PASSWORD)."
        ),
        impact=(
            "Without any user or CONTROL_API_KEYS, the server runs without "
            "authentication (MVP compatibility mode)."
        ),
        remediation="Set CONTROL_ADMIN_USERNAME and CONTROL_ADMIN_PASSWORD, then restart once to bootstrap the admin.",
        validation_rule="Effective only together with CONTROL_ADMIN_PASSWORD.",
        related_checks=["auth_scope"],
        related_pages=["/admin"],
    ),
    SettingMetadata(
        key="CONTROL_ADMIN_PASSWORD",
        display_name="Bootstrap admin password",
        category="auth",
        requiredness="conditional",
        description="Password for the bootstrap admin user. Stored only as a PBKDF2 hash.",
        impact=(
            "Without any user or CONTROL_API_KEYS, the server runs without "
            "authentication (MVP compatibility mode)."
        ),
        remediation="Set CONTROL_ADMIN_USERNAME and CONTROL_ADMIN_PASSWORD, then restart once to bootstrap the admin.",
        validation_rule="Effective only together with CONTROL_ADMIN_USERNAME.",
        related_checks=["auth_scope"],
        related_pages=["/admin"],
    ),
    SettingMetadata(
        key="CONTROL_API_KEYS",
        display_name="Legacy API keys",
        category="auth",
        requiredness="optional",
        description=(
            "Comma-separated legacy service API keys accepted as X-Api-Key. "
            "Enables auth even when no user exists."
        ),
        impact="If empty and no user exists, anyone who can reach the server has full access.",
        remediation="Set CONTROL_API_KEYS, or bootstrap an admin user instead.",
        related_checks=["auth_scope"],
        related_pages=["/admin"],
    ),
]

SETTINGS_BY_KEY = {s.key: s for s in SETTINGS_METADATA}


def get_setting(key: str) -> Optional[SettingMetadata]:
    return SETTINGS_BY_KEY.get(key)
